Description:  AWS demo by monir

Parameters:
  EnvironmentName:
    Description: wp-vpc-environment
    Type: String
    

  VpcCIDR:
    Description: VpcCidr description
    Type: String
    Default: 10.0.0.0/16


Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName




Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC

